name: Run JMeter Tests

on:
  workflow_dispatch:   # allows manual run
  push:
    branches:
      - main

jobs:
  jmeter-test:
    runs-on: windows-latest   # changed from ubuntu to windows

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4   # latest checkout action

      # Step 2: Setup Java (JMeter needs it)
      - name: Setup Java
        uses: actions/setup-java@v4   # updated to v4
        with:
          java-version: '17'   # better for JMeter 5.6.3
          distribution: 'temurin'

      # Step 3: Install JMeter on Windows
      - name: Install JMeter
        run: |
          curl -L https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.zip -o jmeter.zip
          tar -xf jmeter.zip
          echo "${{ github.workspace }}\apache-jmeter-5.6.3\bin" >> $env:GITHUB_PATH

      # Step 4: Run JMeter Test
      - name: Run JMeter script
        run: |
          jmeter -n -t "JMX files/100Items_Drag_and_Drop_Item_Library_Files_API.jmx" -l results.jtl -e -o results/

      # Step 5: Upload report as artifact
      - name: Upload JMeter Report
        uses: actions/upload-artifact@v4   # ✅ latest version
        with:
          name: jmeter-report
          path: results/
