name: Run All JMeter Tests

on:
  workflow_dispatch:
  push:
    branches:
      - develop  # changed to develop branch as you mentioned

jobs:
  jmeter-test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Install JMeter
      - name: Install JMeter
        run: |
          curl -L https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.zip -o jmeter.zip
          tar -xf jmeter.zip
          echo "${{ github.workspace }}\apache-jmeter-5.6.3\bin" >> $env:GITHUB_PATH

      # Step 4: Run all JMX test scripts recursively and generate reports
      - name: Run All JMeter Scripts
        shell: pwsh
        run: |
          $timestamp = Get-Date -Format "yyyy-MM-dd_HHmmss"
          # Recursively get all .jmx files inside BE_Integration Environment folder
          $jmxFiles = Get-ChildItem -Path "BE_Integration Environment" -Filter *.jmx -Recurse
          New-Item -ItemType Directory -Force -Path results | Out-Null

          foreach ($file in $jmxFiles) {
            $baseName = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
            $resultDir = "results/${baseName}_$timestamp"
            New-Item -ItemType Directory -Force -Path $resultDir | Out-Null

            $jtlFile = "$resultDir/${baseName}.jtl"
            $htmlDir = "$resultDir/${baseName}-html"

            Write-Host "Running test: $baseName"
            & "${{ github.workspace }}\apache-jmeter-5.6.3\bin\jmeter.bat" -n -t "$($file.FullName)" -l "$jtlFile"

            Write-Host "Generating report: $htmlDir"
            & "${{ github.workspace }}\apache-jmeter-5.6.3\bin\jmeter.bat" -g "$jtlFile" -o "$htmlDir"
          }

      # Step 5: Upload all reports as artifact
      - name: Upload JMeter Reports
        uses: actions/upload-artifact@v4
        with:
          name: all-jmeter-reports
          path: results/
